# Исключения могут быть выброшены с аргументами, которые дают подробности о них.

name = "123"
raise NameError("Invalid name!")

# Это облегчает понимание другим разработчикам, почему вы вызвали исключение.